export const FETCH_WEATHER_TODAY = 'FETCH_WEATHER_TODAY'
export const FETCH_HOURLY_FORECAST = 'FETCH_HOURLY_FORECAST'
export const FETCH_WEEK_FORECAST = 'FETCH_WEEK_FORECAST'

export const START_LOADING = 'START_LOADING'
export const FINISH_LOADING = 'FINISH_LOADING'
